# Generated by Django 5.0.1 on 2024-01-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Slimfit', 'Slimfit'), ('Relaxed Fit', 'Relaxed fit'), ('Nu se aplica', 'Not Applicable')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Abonament', 'Subscription'), ('Accesoriu', 'Accessory')], max_length=50),
        ),
    ]
