# Generated by Django 5.0.1 on 2024-01-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('subscription', 'Subscription'), ('accessory', 'Accessory')],
                                          max_length=50)),
                ('gender', models.CharField(max_length=1)),
                ('shape', models.CharField(
                    choices=[('regular', 'Regular'), ('slimfit', 'Slimfit'), ('relaxed fit', 'Relaxed fit'),
                             ('not applicable', 'Not Applicable')], max_length=100)),
            ],
        ),
    ]
