# Generated by Django 5.0.1 on 2024-01-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='shape',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Slimfit', 'Slimfit'), ('Relaxed Fit', 'Relaxed fit'), ('Nu se aplica', 'Not Applicable')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('Abonament', 'Subscription'), ('Accesoriu', 'Accessory')], max_length=50),
        ),
    ]
