# Generated by Django 5.0.1 on 2024-01-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sport',
            name='shape',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Slimfit', 'Slimfit'), ('Relaxed Fit', 'Relaxed fit'), ('Nu se aplica', 'Not Applicable')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='type',
            field=models.CharField(choices=[('Abonament', 'Subscription'), ('Accesoriu', 'Accessory')], max_length=50),
        ),
    ]
